[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # Ошибки связанные с кирилицей
    "RUF001", "RUF002", "RUF003",
    # Закоментированный код
    "ERA001",
    # TODO
    "TD003", "FIX002",
    # Обработка ошибок
    "BLE001",
    # Cравнение магических значений
    "PLR2004"
]

[tool.poetry]
name = "pars-diary"
version = "0.1.0"
description = "Проект для улучшения успеваемости учеников, путем внедрения современных технологий."
authors = ["Ivan Melcikov"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
requests = "2.32.3"
matplotlib = "3.10.0"
gradio-client = "1.3.0"
loguru = "0.7.2"
aiogram = "3.12.0"
python-dotenv = "1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
