[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # Ошибки связанные с кирилицей
    "RUF001", "RUF002", "RUF003",
    # Закоментированный код
    "ERA001",
    # TODO
    "TD003", "FIX002",
    # Обработка ошибок
    "BLE001",
    # Cравнение магических значений
    "PLR2004"
]
